<html>
<head>
<title>_timeouts.py</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
.s0 { color: #cc7832;}
.s1 { color: #a9b7c6;}
.s2 { color: #629755; font-style: italic;}
.s3 { color: #6897bb;}
.s4 { color: #6a8759;}
</style>
</head>
<body bgcolor="#2b2b2b">
<table CELLSPACING=0 CELLPADDING=5 COLS=1 WIDTH="100%" BGCOLOR="#606060" >
<tr><td><center>
<font face="Arial, Helvetica" color="#000000">
_timeouts.py</font>
</center></td></tr></table>
<pre><span class="s0">from </span><span class="s1">contextlib </span><span class="s0">import </span><span class="s1">contextmanager</span>

<span class="s0">import </span><span class="s1">trio</span>


<span class="s0">def </span><span class="s1">move_on_at(deadline):</span>
    <span class="s2">&quot;&quot;&quot;Use as a context manager to create a cancel scope with the given 
    absolute deadline. 
 
    Args: 
      deadline (float): The deadline. 
 
    &quot;&quot;&quot;</span>
    <span class="s0">return </span><span class="s1">trio.CancelScope(deadline=deadline)</span>


<span class="s0">def </span><span class="s1">move_on_after(seconds):</span>
    <span class="s2">&quot;&quot;&quot;Use as a context manager to create a cancel scope whose deadline is 
    set to now + *seconds*. 
 
    Args: 
      seconds (float): The timeout. 
 
    Raises: 
      ValueError: if timeout is less than zero. 
 
    &quot;&quot;&quot;</span>

    <span class="s0">if </span><span class="s1">seconds &lt; </span><span class="s3">0</span><span class="s1">:</span>
        <span class="s0">raise </span><span class="s1">ValueError(</span><span class="s4">&quot;timeout must be non-negative&quot;</span><span class="s1">)</span>
    <span class="s0">return </span><span class="s1">move_on_at(trio.current_time() + seconds)</span>


<span class="s0">async def </span><span class="s1">sleep_forever():</span>
    <span class="s2">&quot;&quot;&quot;Pause execution of the current task forever (or until cancelled). 
 
    Equivalent to calling ``await sleep(math.inf)``. 
 
    &quot;&quot;&quot;</span>
    <span class="s0">await </span><span class="s1">trio.lowlevel.wait_task_rescheduled(</span><span class="s0">lambda </span><span class="s1">_: trio.lowlevel.Abort.SUCCEEDED)</span>


<span class="s0">async def </span><span class="s1">sleep_until(deadline):</span>
    <span class="s2">&quot;&quot;&quot;Pause execution of the current task until the given time. 
 
    The difference between :func:`sleep` and :func:`sleep_until` is that the 
    former takes a relative time and the latter takes an absolute time 
    according to Trio's internal clock (as returned by :func:`current_time`). 
 
    Args: 
        deadline (float): The time at which we should wake up again. May be in 
            the past, in which case this function executes a checkpoint but 
            does not block. 
 
    &quot;&quot;&quot;</span>
    <span class="s0">with </span><span class="s1">move_on_at(deadline):</span>
        <span class="s0">await </span><span class="s1">sleep_forever()</span>


<span class="s0">async def </span><span class="s1">sleep(seconds):</span>
    <span class="s2">&quot;&quot;&quot;Pause execution of the current task for the given number of seconds. 
 
    Args: 
        seconds (float): The number of seconds to sleep. May be zero to 
            insert a checkpoint without actually blocking. 
 
    Raises: 
        ValueError: if *seconds* is negative. 
 
    &quot;&quot;&quot;</span>
    <span class="s0">if </span><span class="s1">seconds &lt; </span><span class="s3">0</span><span class="s1">:</span>
        <span class="s0">raise </span><span class="s1">ValueError(</span><span class="s4">&quot;duration must be non-negative&quot;</span><span class="s1">)</span>
    <span class="s0">if </span><span class="s1">seconds == </span><span class="s3">0</span><span class="s1">:</span>
        <span class="s0">await </span><span class="s1">trio.lowlevel.checkpoint()</span>
    <span class="s0">else</span><span class="s1">:</span>
        <span class="s0">await </span><span class="s1">sleep_until(trio.current_time() + seconds)</span>


<span class="s0">class </span><span class="s1">TooSlowError(Exception):</span>
    <span class="s2">&quot;&quot;&quot;Raised by :func:`fail_after` and :func:`fail_at` if the timeout 
    expires. 
 
    &quot;&quot;&quot;</span>


<span class="s1">@contextmanager</span>
<span class="s0">def </span><span class="s1">fail_at(deadline):</span>
    <span class="s2">&quot;&quot;&quot;Creates a cancel scope with the given deadline, and raises an error if it 
    is actually cancelled. 
 
    This function and :func:`move_on_at` are similar in that both create a 
    cancel scope with a given absolute deadline, and if the deadline expires 
    then both will cause :exc:`Cancelled` to be raised within the scope. The 
    difference is that when the :exc:`Cancelled` exception reaches 
    :func:`move_on_at`, it's caught and discarded. When it reaches 
    :func:`fail_at`, then it's caught and :exc:`TooSlowError` is raised in its 
    place. 
 
    Raises: 
      TooSlowError: if a :exc:`Cancelled` exception is raised in this scope 
        and caught by the context manager. 
 
    &quot;&quot;&quot;</span>

    <span class="s0">with </span><span class="s1">move_on_at(deadline) </span><span class="s0">as </span><span class="s1">scope:</span>
        <span class="s0">yield </span><span class="s1">scope</span>
    <span class="s0">if </span><span class="s1">scope.cancelled_caught:</span>
        <span class="s0">raise </span><span class="s1">TooSlowError</span>


<span class="s0">def </span><span class="s1">fail_after(seconds):</span>
    <span class="s2">&quot;&quot;&quot;Creates a cancel scope with the given timeout, and raises an error if 
    it is actually cancelled. 
 
    This function and :func:`move_on_after` are similar in that both create a 
    cancel scope with a given timeout, and if the timeout expires then both 
    will cause :exc:`Cancelled` to be raised within the scope. The difference 
    is that when the :exc:`Cancelled` exception reaches :func:`move_on_after`, 
    it's caught and discarded. When it reaches :func:`fail_after`, then it's 
    caught and :exc:`TooSlowError` is raised in its place. 
 
    Raises: 
      TooSlowError: if a :exc:`Cancelled` exception is raised in this scope 
        and caught by the context manager. 
      ValueError: if *seconds* is less than zero. 
 
    &quot;&quot;&quot;</span>
    <span class="s0">if </span><span class="s1">seconds &lt; </span><span class="s3">0</span><span class="s1">:</span>
        <span class="s0">raise </span><span class="s1">ValueError(</span><span class="s4">&quot;timeout must be non-negative&quot;</span><span class="s1">)</span>
    <span class="s0">return </span><span class="s1">fail_at(trio.current_time() + seconds)</span>
</pre>
</body>
</html>